### ISSUE TITLE
UI Bug - Firefox - Crashing on click.

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/platform-ui#427] opened 2019-08-12 16:38 UTC
### How to Reproduce
1. Go to landing page
2. Log in
3. Click pretty much anywhere on the page after UI loads post successful login

![image](https://user-images.githubusercontent.com/6350043/62881544-0306c080-bcfe-11e9-9316-3580e87cc136.png)

event.path is a chrome propoerty, does not exist in firefox

**Comment by rosibaj** [comment] 2019-08-28 21:22
@andricDu is this happening to you still? it worked for me on windows so wondering if linux specific?

**Comment by rosibaj** [comment] 2019-08-29 14:38
@joneubank configure browserstack to run against firefox and chrome!

**Comment by akachru-github** [comment] 2019-08-29 18:46
For what it's worth, I cannot repro this on FF on MacOS. 
Login is successful and application seems to be operating normally (although I cannot get the user profile open at all in FF, but that is a different problem.)

**Comment by joneubank** [comment] 2019-09-05 19:50
Can't reproduce anymore. Added firefox config for browserstack and made the default local browserstack execution run on chrome and firefox.

**Comment by rosibaj** [comment] 2019-09-05 20:20
@joneubank is the browserstack change merged to qa already?

**Comment by joneubank** [comment] 2019-09-05 20:21
PR is merged, but, browserstack testing isn't configured to automatically run yet and there are very few tests written... so... not really. Can be manually triggered at any point though via command line.

**Comment by rosibaj** [comment] 2019-09-05 20:23
sound good - will just close this issue for now then!

**Closed by rosibaj** 2019-09-05 20:23 UTC
Labels: SP:1, bug
