### ISSUE TITLE
🐛 Clicking options on contact page dropdown does nothing.

### ISSUE THREAD

**Issue by P-Saha** [icgc-argo/platform-ui#1229] opened 2020-03-18 18:07 UTC
## Describe the bug
When trying to use send a message and selecting an option from "What do you need assistance with?", nothing happens, as if nothing was selected.

## Steps To Reproduce
Both in qa and dev.
Navigate to:
https://platform-ui.dev.argo.cancercollaboratory.org/contact
https://platform-ui.qa.argo.cancercollaboratory.org/contact

Steps to reproduce the behaviour:
In send message box, click on the dropdown and select something.

## Expected behaviour
The option I selected to show up and for the dropdown to behave normally.

**Comment by rosibaj** [comment] 2020-03-26 05:31
Closing this issue as it is not a bug - the form hookup has not be done yet so this will be handled with that #290

**Closed** 2020-03-26 05:32 UTC
Labels: bug, wont-do
