### ISSUE TITLE
🐛 Redirecting to old login page

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1428] opened 2020-05-04 19:13 UTC
## Describe the bug
When logging out from certain program pages, the user is redirected to the old login page or is stuck on the loader.

## Steps To Reproduce
For example, go to to CYUNG-CA dashboard and log out. The page is frozen with the dna loader

Or go to RAWR-CA dashboard and log out. User is quickly redirected to old login page https://platform-ui.qa.argo.cancercollaboratory.org/login?redirect=/submission/program

## Expected behaviour
They should be redirected to the new homepage (never to this login page)

**Comment by anncatton** [comment] 2020-05-05 15:23
Looks like this is partially linked to #1357

**Comment by rosibaj** [comment] 2020-05-05 16:17
@anncatton if you find both are related, we can pull both in.

**Comment by anncatton** [comment] 2020-05-05 16:28
I don't think the issues are related, I think this ticket might be describing 2 separate issues. @hlminh2000 pointed out the loader issue recently.

**Comment by hlminh2000** [comment] 2020-05-05 18:07
yeah I think they're separate...

**Comment by anncatton** [comment] 2020-05-26 16:17
The PR for this does not entirely fix the endless loader issue, that will be addressed in https://github.com/icgc-argo/platform-ui/issues/1357

**Comment by rosibaj** [comment] 2020-05-26 22:35
@anncatton if i click the link in the ticket i still get sent to the old page...

**Comment by rosibaj** [comment] 2020-05-28 21:13
confirmed on prod logout goes to homepage

**Closed by rosibaj** 2020-05-28 21:13 UTC
Labels: 1.26.0, SP:3, bug
