### ISSUE TITLE
🐛 Sidebar Scrolling is "sticky"

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/platform-ui#822] opened 2019-10-28 17:50 UTC
## Describe the bug
On the all programs screen, when you scroll down the sidebar it will stop scrolling after a moment of scrolling. If you keep attempting to scroll it will continue scrolling down after a brief pause, but then stop again after the same short distance.

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to All Programs
2. Use mouse wheel to scroll sidebar
3. Notice how the scrolling is sticking as described above.

## Expected behaviour
Smooth scrolling like all other windows.

**Comment by rosibaj** [comment] 2020-03-26 05:19
@joneubank @kcullion are you guys still seeing this issue?  I am unable to replicate on windows + chrome?

**Comment by joneubank** [comment] 2020-03-26 05:30
@rosibaj Cannot reproduce in dev... I am testing by shrinking the window to give the scroll bar. might need many more programs to see the problem. Would be interesting to generate a bunch of test programs and see if we have the issue.

**Comment by kcullion** [comment] 2020-03-26 13:14
@rosibaj @joneubank I dont think I see this issue either. I did notice when you make your screen small and scroll the sidebar, then scroll the main program table area - the sidebar scrolls up more so that the bottom of it isn't inline with the bottom of the browser. Probably an edge case though.
<img width="894" alt="Screen Shot 2020-03-26 at 9 14 34 AM" src="https://user-images.githubusercontent.com/18424138/77650684-3a02ad00-6f42-11ea-9403-540992b7295c.png">

**Comment by rosibaj** [comment] 2020-03-27 15:24
ok - since its not reproducible i am going to close this issue for now.

**Closed by rosibaj** 2020-03-27 15:24 UTC
Labels: bug, wont-do
