### ISSUE TITLE
New dictionary banner

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1291] opened 2020-04-01 14:11 UTC
- [ ] When the submitter doesn't have an invalid submission and just needs to be notified that the dictionary is updated, this link exists in this blue banner too. *** I'm not sure if this banner has been implemented yet??
<img width="1178" alt="Screen Shot 2020-03-06 at 11 37 39 AM" src="https://user-images.githubusercontent.com/18424138/76103083-154c9280-5f9f-11ea-8e42-03db5a47d05c.png">

**Comment by kcullion** [comment] 2021-11-15 15:26
Closing this as it's a duplicate of: https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/952

**Closed by kcullion** 2021-11-15 15:26 UTC
