### ISSUE TITLE
Dashboard Sorting issues in Prod (OCCAMS-GB, PACA-CA)

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#1867] opened 2021-03-15 19:04 UTC
For OCCAMS-GB, sorting by the following columns result in infinite spinner
- Donor ID
- Core Completion
- Samples
- Raw Reads
- Sanger VC
- Last Updated
- (no problem with Alignment and Mutect2 VC)

For PACA-CA, sorting by the following columns result in infinite spinner
- Donor ID
- Core Completion
- Samples
- Alignment
- Sanger VC
- Last Updated
- (no problem with Raw Reads and Mutect2 VC)

Other programs (APGI-AU, LUCA-KR, MUTO-INTL, PTS-SA) have no issues.

![image](https://user-images.githubusercontent.com/15824252/111322999-e0f2c400-863f-11eb-9b58-074057612116.png)

**Comment by rosibaj** [comment] 2021-03-16 19:43
Was fixed in production by @joneubank. 


Root cause identified and will be fixed in: https://github.com/icgc-argo/donor-submission-aggregator/issues

**Closed by rosibaj** 2021-03-16 19:43 UTC
Labels: bug, critical, production
